In [1]:
import numpy as np

In [10]:
# ndarray class로부터 객체를 생성한다. 
ar = np.array([_ for _ in range(10)])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
type(ar)

numpy.ndarray

In [17]:
ar.shape
# (10,) -> 1차원의 10칸 갖는 ndarray라는 뜻임. shape이라는 것을 통해 모양을 유추할 수 있음

1

In [13]:
len(ar)

10

In [16]:
c = np.array([[10,20,30,40],
              [50,60,70,80]])
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [23]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a[0,:3] #1,2,3의 값을 가져오기 

array([1, 2, 3])

In [25]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a[:2][:3]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [47]:
m = np.array([[0,1,2,3,4],[5,6,7,8,900],[10,11,12,13,14]])
print(m)

print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:,2])
print(m[:2,3:])

[[  0   1   2   3   4]
 [  5   6   7   8 900]
 [ 10  11  12  13  14]]
7
14
[6 7]
[ 7 12]
[[  3   4]
 [  8 900]]


In [44]:
a =[1,2,3,4,5]
a[3:4]

[4]

In [50]:
e = np.zeros((5,2) ,dtype='i')
print(e)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [65]:
m = np.arange(12)
print(m)

n = m.reshape(3,4)
print(n)

print()
o = m.reshape(2,3,2)
print(o)

print()
i = o.flatten()
print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
n[:2, np.newaxis]

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [92]:
a = np.ones((4,2))
b = np.zeros((4,2))
c = np.array([['a','b'],['c','d'],['e','f'],['g','h']])

print(a.shape)
print(a)
print()
print(b)
print()
print(c)


(4, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']]


In [105]:
d = np.stack([a,b,c], axis=2)
print(d)
d.shape

[[['1.0' '0.0' 'a']
  ['1.0' '0.0' 'b']]

 [['1.0' '0.0' 'c']
  ['1.0' '0.0' 'd']]

 [['1.0' '0.0' 'e']
  ['1.0' '0.0' 'f']]

 [['1.0' '0.0' 'g']
  ['1.0' '0.0' 'h']]]


(4, 2, 3)

In [114]:
a = np.arange(6).reshape(3,2)
print(a)

b = np.tile(a, (2,3))
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]


In [138]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.arange(10,151,10).reshape(3,5)


d = np.hstack([a,b])
e = np.vstack([d,c])
f = np.tile(e,(2,1))
# print(d)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [158]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

np.max(practice)
np.sum(practice, axis=0)
np.max(practice, axis=0)
np.mean(practice, axis=1)
np.min(practice, axis=1)

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]
5.333333333333333


In [159]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [160]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [162]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [190]:
scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])
print(scores)
print()

print(scores[:,[2,1,3,0]])
print(scores[:,np.array[46,99,100,71]])

[[  1   2   3   4]
 [ 46  99 100  71]
 [ 81  59  90 100]]

[[  3   2   4   1]
 [100  99  71  46]
 [ 90  59 100  81]]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [177]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [188]:
np.random.seed(0)


In [186]:
a = np.random.choice(2, 100, p=[0.5, 0.5])
print(a)
np.mean(a)

[1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1
 1 1 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1
 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0]


0.49

In [189]:
a = np.random.choice(2, 100)
print(a)
np.mean(a)

[0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0
 0 1 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0]


0.56